from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class RuntimeWorkflowState(str, Enum):
    """
    Durable runtime state machine states for a persisted workflow session.
    """
    CREATED = "CREATED"
    PLANNING = "PLANNING"
    EXECUTING = "EXECUTING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class PlanStep(BaseModel):
    """
    Represents a single step in the execution plan generated by the Planner.
    Supports dependency tracking for DAG resolution.
    """
    step_id: str = Field(..., description="Unique identifier for the step")
    tool: str = Field(..., description="The name of the tool to be executed")
    reason: str = Field(..., description="The reasoning behind selecting this tool")
    depends_on: List[str] = Field(default_factory=list, description="List of step_ids this step depends on")
    status: str = Field("pending", description="Status: pending | running | completed | failed")

class ExecutionPlan(BaseModel):
    """
    Represents a complete dynamic plan containing ordered/dep-resolved steps.
    """
    plan: List[PlanStep] = Field(default_factory=list)

class ToolResult(BaseModel):
    """
    Strongly typed contract for all tools execution outcomes.
    """
    status: str = Field(..., description="Execution status: success | error")
    confidence: float = Field(0.0, description="Confidence score from 0.0 to 1.0")
    artifacts: Dict[str, Any] = Field(default_factory=dict, description="Structured outputs produced by the tool")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata such as execution logs, source info, etc.")
    retryable: bool = Field(True, description="Whether the tool error is transient and retryable")
    error_message: Optional[str] = Field(None, description="Detailed error message if failed")

class EvaluatorOutput(BaseModel):
    """
    Represents the output from the Evaluator self-correction loop.
    """
    score: float = Field(..., description="Quality score from 0.0 to 1.0")
    reasoning: str = Field(..., description="Critique reasoning")
    passed: bool = Field(..., description="True if draft passes quality audit")
    corrections: List[str] = Field(default_factory=list, description="Specific feedback items to correct")

class ReasoningTrace(BaseModel):
    """
    Agentic reasoning traces showing high-level decisions.
    """
    decision: str = Field(..., description="Action taken or decided")
    reason: str = Field(..., description="Reasoning for the decision")
    timestamp: str = Field(..., description="ISO 8601 UTC timestamp")

class WorkflowSession(BaseModel):
    """
    Central database-persisted session tracking the durable state machine execution.
    """
    task_id: str = Field(..., description="Unique task identifier")
    status: RuntimeWorkflowState = Field(RuntimeWorkflowState.CREATED, description="Current runtime workflow state")
    user_prompt: str = Field(..., description="Original prompt text")
    execution_plan: ExecutionPlan = Field(default_factory=ExecutionPlan, description="Dynamic plan")
    workflow_state_json: str = Field("{}", description="Serialized legacy WorkflowState string for tools compatibility")
    websocket_session_metadata: Dict[str, Any] = Field(default_factory=dict, description="WS parameters")
    approval_state: Optional[str] = Field(None, description="Current approval step status")
    rejection_feedback: Optional[str] = Field(None, description="User rejection feedback text")
    created_at: str = Field(..., description="Creation ISO timestamp")
    updated_at: str = Field(..., description="Update ISO timestamp")
    workflow_version: int = Field(1, description="Concurrency tracking version")
    event_history: List[Dict[str, Any]] = Field(default_factory=list, description="Audit trail of state transitions")
    retries_count: int = Field(0, description="Total tool execution retry attempts")
    memory_context: Optional[str] = Field(None, description="Prior successful workflow preferences context")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Workflow execution performance metrics")


# Backward compatibility for older imports/tests while new code uses RuntimeWorkflowState.
CoreWorkflowState = RuntimeWorkflowState
