export const SERVER_EVENTS = {
  STATUS_UPDATE: 'STATUS_UPDATE',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_CANCELLED: 'TASK_CANCELLED',
  ERROR: 'ERROR',
  PING: 'PING',
  PONG: 'PONG',
} as const;

export const CLIENT_EVENTS = {
  START_TASK: 'START_TASK',
  APPROVAL_RESPONSE: 'APPROVAL_RESPONSE',
  STOP: 'STOP',
  PONG: 'PONG',
} as const;
