export const SERVER_EVENTS = {
  STATUS_UPDATE: 'STATUS_UPDATE',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_CANCELLED: 'TASK_CANCELLED',
  ERROR: 'ERROR',
} as const;

export const CLIENT_EVENTS = {
  APPROVED: 'APPROVED',
  STOP: 'STOP',
} as const;
