import pytest
from unittest.mock import AsyncMock, MagicMock
from app.services.llm_service import generate_outreach_draft, self_reflect_draft, MAX_OUTPUT_LENGTH

@pytest.mark.asyncio
async def test_generate_outreach_draft(mock_openai):
    # Set up mock response
    mock_choice = MagicMock()
    mock_choice.message.content = "   This is a mock draft message.   "
    mock_response = MagicMock()
    mock_response.choices = [mock_choice]
    mock_openai.return_value = mock_response
    
    prompt = "Find computer hardware vendors"
    analysis_summary = "Option A is $500. Option B is $600."
    selected_vendor = {"name": "Test Vendor", "location": "Bangalore"}
    
    result = await generate_outreach_draft(prompt, analysis_summary, selected_vendor)
    assert result == "This is a mock draft message."
    
    # Verify mock call parameters
    mock_openai.assert_called_once()
    call_args = mock_openai.call_args[1]
    assert call_args["messages"][1]["content"] is not None

@pytest.mark.asyncio
async def test_generate_outreach_draft_empty_response(mock_openai):
    mock_choice = MagicMock()
    mock_choice.message.content = "   "
    mock_response = MagicMock()
    mock_response.choices = [mock_choice]
    mock_openai.return_value = mock_response
    
    with pytest.raises(ValueError, match="Empty draft generated by LLM"):
        await generate_outreach_draft("prompt", "summary")

@pytest.mark.asyncio
async def test_self_reflect_draft_two_pass(mock_openai):
    # Pass 1: internal evaluation response
    mock_choice_1 = MagicMock()
    mock_choice_1.message.content = "Evaluation: Tone is a bit informal."
    mock_response_1 = MagicMock()
    mock_response_1.choices = [mock_choice_1]
    
    # Pass 2: rewritten draft response
    mock_choice_2 = MagicMock()
    mock_choice_2.message.content = "Dear vendor, this is a refined email draft."
    mock_response_2 = MagicMock()
    mock_response_2.choices = [mock_choice_2]
    
    mock_openai.side_effect = [mock_response_1, mock_response_2]
    
    result = await self_reflect_draft(
        draft="Dear vendor, hello.",
        prompt="Ask for pricing.",
        rejection_feedback="Make it formal"
    )
    
    assert result == "Dear vendor, this is a refined email draft."
    assert mock_openai.call_count == 2

@pytest.mark.asyncio
async def test_self_reflect_draft_sanitization_leaked_preamble(mock_openai):
    # Pass 1: internal evaluation response
    mock_choice_1 = MagicMock()
    mock_choice_1.message.content = "Evaluation: Tone is informal."
    mock_response_1 = MagicMock()
    mock_response_1.choices = [mock_choice_1]
    
    # Pass 2: rewritten draft with leaked evaluation preamble
    mock_choice_2 = MagicMock()
    mock_choice_2.message.content = (
        "Here is my evaluation and critique of the draft. "
        "The rating is 8/10.\n\n"
        "Subject: Request for server quote\n"
        "Dear Supplier,\n"
        "Please send us a quote."
    )
    mock_response_2 = MagicMock()
    mock_response_2.choices = [mock_choice_2]
    
    mock_openai.side_effect = [mock_response_1, mock_response_2]
    
    result = await self_reflect_draft(
        draft="Dear Supplier, hi.",
        prompt="Request quotes."
    )
    
    # Preamble should be stripped and result should start with the email content
    assert result.startswith("Subject: Request for server quote")
    assert "critique" not in result
    assert "rating" not in result

@pytest.mark.asyncio
async def test_self_reflect_draft_sanitization_markdown_artifacts(mock_openai):
    mock_choice_1 = MagicMock()
    mock_choice_1.message.content = "Evaluation: Good."
    mock_response_1 = MagicMock()
    mock_response_1.choices = [mock_choice_1]
    
    mock_choice_2 = MagicMock()
    # Leaks markdown backticks and headings
    mock_choice_2.message.content = "```\n# Outreach Email\nDear Partner,\n...\n```"
    mock_response_2 = MagicMock()
    mock_response_2.choices = [mock_choice_2]
    
    mock_openai.side_effect = [mock_response_1, mock_response_2]
    
    result = await self_reflect_draft("Partner...", "Task...")
    
    assert not result.startswith("```")
    assert not result.startswith("#")
    assert "Dear Partner" in result

@pytest.mark.asyncio
async def test_self_reflect_draft_truncation(mock_openai):
    mock_choice_1 = MagicMock()
    mock_choice_1.message.content = "Good."
    mock_response_1 = MagicMock()
    mock_response_1.choices = [mock_choice_1]
    
    mock_choice_2 = MagicMock()
    long_content = "A" * (MAX_OUTPUT_LENGTH + 100)
    mock_choice_2.message.content = long_content
    mock_response_2 = MagicMock()
    mock_response_2.choices = [mock_choice_2]
    
    mock_openai.side_effect = [mock_response_1, mock_response_2]
    
    result = await self_reflect_draft("draft", "prompt")
    assert len(result) == MAX_OUTPUT_LENGTH
