from openai import AsyncOpenAI
from app.core import config
from app.core.logger import get_logger

logger = get_logger("services.llm")

# Initialize centrally once using OPENAI_API_KEY
client = AsyncOpenAI(api_key=config.OPENAI_API_KEY)

# Maximum allowed output length for defensive truncation
MAX_OUTPUT_LENGTH = 2000

async def generate_outreach_draft(prompt: str, analysis_summary: str) -> str:
    """
    Generates a professional and concise vendor outreach message using the user's
    task prompt and analysis summary for context.
    """
    logger.info("Draft generation started")
    response = await client.chat.completions.create(
        model=config.OPENAI_MODEL,
        messages=[
            {
                "role": "system",
                "content": "You are a professional procurement assistant. Generate extremely concise vendor outreach messages."
            },
            {
                "role": "user",
                "content": (
                    f"Task: {prompt}\n\n"
                    f"Analysis: {analysis_summary}\n\n"
                    f"Generate a concise professional outreach message for the above task."
                )
            }
        ],
        temperature=config.OPENAI_TEMPERATURE,
        max_tokens=150
    )
    draft = response.choices[0].message.content.strip()
    
    # Validate LLM output
    if not draft:
        logger.warning("LLM returned empty draft output")
        raise ValueError("Empty draft generated by LLM")
    
    # Defensive truncation
    draft = draft[:MAX_OUTPUT_LENGTH]
    
    logger.info("Draft generation completed")
    return draft

async def self_reflect_draft(draft: str, prompt: str) -> str:
    """
    Reviews and improves an outreach message for professionalism, tone, and clarity
    while keeping it concise and aligned with the original task prompt.
    """
    logger.info("Self-reflection started")
    response = await client.chat.completions.create(
        model=config.OPENAI_MODEL,
        messages=[
            {
                "role": "system",
                "content": "You are reviewing an outreach message for professionalism, tone, and clarity. Keep it concise."
            },
            {
                "role": "user",
                "content": (
                    f"Original task: {prompt}\n\n"
                    f"Improve this outreach draft while keeping it concise and professional:\n\n{draft}"
                )
            }
        ],
        temperature=config.OPENAI_TEMPERATURE,
        max_tokens=150
    )
    improved = response.choices[0].message.content.strip()
    
    # Validate LLM output
    if not improved:
        logger.warning("LLM returned empty self-reflection output")
        raise ValueError("Empty self-reflection output generated by LLM")
    
    # Defensive truncation
    improved = improved[:MAX_OUTPUT_LENGTH]
    
    logger.info("Self-reflection completed")
    return improved
