import json
import re
from typing import Optional

from openai import AsyncOpenAI

from app.core import config
from app.core.logger import get_logger
from app.utils.retry import retry_with_backoff

logger = get_logger("services.llm")

# Maximum allowed output length for defensive truncation
MAX_OUTPUT_LENGTH = 2000

# ---------------------------------------------------------------------------
# Provider-aware client & model helpers
# ---------------------------------------------------------------------------

def _get_client() -> AsyncOpenAI:
    """
    Returns the appropriate AsyncOpenAI client based on AGENT_PROVIDER.

    - For "openai": uses OPENAI_API_KEY (standard OpenAI endpoint).
    - For "ollama": points base_url at the local Ollama OpenAI-compatible server.
    """
    if config.AGENT_PROVIDER == "ollama":
        # Ollama's OpenAI-compatible endpoint; api_key may be empty or a
        # user-configured key if the Ollama setup requires one.
        return AsyncOpenAI(
            api_key=config.OPENAI_API_KEY or "ollama",
            base_url=config.OLLAMA_BASE_URL,
        )
    # Default: standard OpenAI
    return AsyncOpenAI(api_key=config.OPENAI_API_KEY)


def _get_model() -> str:
    """Returns the model name for the currently configured AGENT_PROVIDER."""
    if config.AGENT_PROVIDER == "ollama":
        return config.OLLAMA_MODEL
    return config.OPENAI_MODEL


# Shared client instance – created lazily so config is fully resolved.
_client: Optional[AsyncOpenAI] = None


def get_client() -> AsyncOpenAI:
    global _client
    if _client is None:
        _client = _get_client()
    return _client


# ---------------------------------------------------------------------------
# Token usage logging helper
# ---------------------------------------------------------------------------

def _log_llm_used(step_name: str) -> None:
    """Log a clear 'llm used' message with provider and model name."""
    logger.info(
        "llm used : %s (%s provider)",
        _get_model(),
        config.AGENT_PROVIDER,
        extra={
            "llm_step": step_name,
            "model": _get_model(),
            "provider": config.AGENT_PROVIDER,
        },
    )


def _log_usage(step_name: str, response) -> None:
    """Log model name and token usage from an OpenAI-compatible response."""
    usage = getattr(response, "usage", None)
    if usage:
        logger.info(
            "Step=%s Model=%s PromptTokens=%s CompletionTokens=%s TotalTokens=%s",
            step_name,
            getattr(response, "model", _get_model()),
            getattr(usage, "prompt_tokens", "?"),
            getattr(usage, "completion_tokens", "?"),
            getattr(usage, "total_tokens", "?"),
            extra={
                "llm_step": step_name,
                "model": getattr(response, "model", _get_model()),
                "prompt_tokens": getattr(usage, "prompt_tokens", None),
                "completion_tokens": getattr(usage, "completion_tokens", None),
                "total_tokens": getattr(usage, "total_tokens", None),
            },
        )
    else:
        # Ollama may not return usage info in all configurations
        logger.info(
            "Step=%s Model=%s (no token usage reported by provider)",
            step_name,
            _get_model(),
        )


# ---------------------------------------------------------------------------
# Shared helper: safe LLM chat completion call
# ---------------------------------------------------------------------------

@retry_with_backoff()
async def _llm_call(
    step_name: str,
    system_prompt: str,
    user_content: str,
    temperature: float = config.OPENAI_TEMPERATURE,
    max_tokens: int = 500,
) -> str:
    """Makes an LLM chat completion call and returns the content string."""
    _log_llm_used(step_name)
    try:
        response = await get_client().chat.completions.create(
            model=_get_model(),
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content},
            ],
            temperature=temperature,
            max_tokens=max_tokens,
        )
    except Exception as e:
        logger.exception("LLM request failed during %s (provider=%s)", step_name, config.AGENT_PROVIDER)
        raise
    _log_usage(step_name, response)
    text = response.choices[0].message.content.strip()
    if not text:
        logger.warning("LLM returned empty output for %s", step_name)
        raise ValueError(f"Empty output generated by LLM for {step_name}")
    return text[:MAX_OUTPUT_LENGTH]


async def generate_execution_result(prompt: str, improved_draft: Optional[str], draft: Optional[str]) -> str:
    """
    Uses LLM to generate the final execution result after approval.
    Produces a realistic delivery confirmation relevant to the topic.
    """
    logger.info("Execution result generation started (provider=%s, model=%s)", config.AGENT_PROVIDER, _get_model())

    final_draft = improved_draft or draft or ""

    system_prompt = (
        "You are a workflow execution system. Generate a brief execution result "
        "confirming that the approved outreach has been delivered. "
        "Be realistic, professional, and relevant to the original task topic."
    )

    user_content = (
        f"Task: {prompt}\n\n"
        f"Outreach message:\n{final_draft}\n\n"
        f"Generate a brief execution confirmation result describing the delivery outcome."
    )

    try:
        result = await _llm_call("generate_execution_result", system_prompt, user_content, max_tokens=200)
        logger.info("Execution result generation completed")
        return result
    except (ValueError, Exception) as e:
        logger.warning("LLM execution result generation failed, using fallback: %s", e)
        return f"Approved workflow executed successfully for task: {prompt[:100]}..."


# ---------------------------------------------------------------------------
# Existing LLM call helpers (draft & reflection)
# ---------------------------------------------------------------------------


def _run_outreach_safety_checks(draft: str, selected_vendor: Optional[dict]) -> tuple[bool, list[str]]:
    """
    Runs programmatic checks on the outreach draft for safety and correctness.
    """
    issues = []
    if not draft or not draft.strip():
        issues.append("Empty draft generated.")
        return False, issues
        
    draft_lower = draft.lower()
    
    # 1. Missing vendor name / placeholders check
    placeholders = ["[vendor", "[recipient", "[first name", "[last name", "[contact name", "[company name", "<company name>", "<vendor name>"]
    for ph in placeholders:
        if ph in draft_lower:
            issues.append(f"Found placeholder text: '{ph}'")
            
    # 2. Aggressive tone check
    aggressive_words = ["must immediately", "pay now", "or else", "demand", "warn you", "failure to comply", "force us"]
    for word in aggressive_words:
        if word in draft_lower:
            issues.append(f"Detected aggressive language: '{word}'")
            
    return len(issues) == 0, issues


async def generate_outreach_draft(prompt: str, analysis_summary: str, selected_vendor: Optional[dict] = None, user_feedback: Optional[str] = None, memory_context: Optional[str] = None) -> str:
    """
    Generates a professional and concise vendor outreach message using the user's
    task prompt, analysis summary, and optional user feedback for context.
    User feedback guides tone and content.
    Memory context enforces critical constraints (e.g., vendor selection must not be overridden).
    Returns the outreach email draft.
    """
    logger.info("Draft generation started (provider=%s, model=%s)", config.AGENT_PROVIDER, _get_model())


    location_context = (
        f"Procurement region:\n"
        f"City: {config.DEFAULT_CITY}\n"
        f"Locality: {config.DEFAULT_LOCALITY}\n"
        f"Pincode: {config.DEFAULT_PINCODE}"
    )

    vendor_context = ""
    if selected_vendor:
        vendor_name = selected_vendor.get('vendor_name') or selected_vendor.get('name', 'Vendor')
        vendor_location = selected_vendor.get('location', 'Unknown Location')
        vendor_context = (
            f"Preferred vendor:\n"
            f"{vendor_name} located in {vendor_location}"
        )

    feedback_context = ""
    if user_feedback and user_feedback.strip():
        feedback_context = (
            "Mandatory user feedback/instructions. These override generic email style rules when they conflict:\n"
            f"{user_feedback}\n\n"
        )

    user_content = (
        f"{location_context}\n\n"
        f"{vendor_context}\n\n"
        f"{feedback_context}"
        f"Task: {prompt}\n\n"
        f"Analysis: {analysis_summary}\n\n"
        f"Generate a concise, realistic, professional vendor outreach email incorporating the user's preferences.\n\n"
        f"Sign the message as:\n"
        f"{config.DEFAULT_USER_NAME}\n"
        f"{config.DEFAULT_COMPANY_NAME}"
    )

    # Build system prompt asking for structured JSON output
    system_prompt = (
        "You are a professional procurement assistant. Write a concise, professional vendor outreach email. "
        "Address the email directly to the vendor company by name (e.g., 'Dear TechNova Systems Team,'). "
        "NEVER use placeholder text such as [Recipient's Last Name], [First Name], [Contact Name], "
        "[Vendor Name], or any bracket placeholders.\n"
        "You MUST obey user feedback exactly. If the user asks for a one-liner, produce one sentence only. "
        "If the user asks for a language, write the draft in that language. "
        "Do not expand the draft beyond the user's requested length or format.\n\n"
        "Return a JSON object of this structure:\n"
        "{\n"
        '  "draft": "email text...",\n'
        '  "issues_found": ["Tone was too pushy"],\n'
        '  "improvements_made": ["Made it more professional"],\n'
        '  "confidence": 0.87\n'
        "}\n"
        "Return ONLY the raw JSON object. Do not include markdown formatting or explanation."
    )
    if memory_context:
        system_prompt = f"{system_prompt}\n\n{memory_context}"

    _log_llm_used("generate_outreach_draft")

    logger.info("LLM System Prompt:\n%s", system_prompt)
    logger.info("LLM User Content:\n%s", user_content)
    try:
        response = await get_client().chat.completions.create(
            model=_get_model(),
            messages=[
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user",
                    "content": user_content
                }
            ],
            temperature=config.OPENAI_TEMPERATURE,
            max_tokens=1000
        )
    except Exception as e:
        logger.exception("LLM request failed during draft generation (provider=%s)", config.AGENT_PROVIDER)
        raise

    _log_usage("generate_outreach_draft", response)
    raw_response = response.choices[0].message.content.strip()

    # Parse structured output JSON
    email_draft = ""
    try:
        json_match = re.search(r'\{.*\}', raw_response, re.DOTALL)
        if json_match:
            raw_json = json_match.group(0)
            data = json.loads(raw_json)
            email_draft = data.get("draft", "").strip()
            issues_found = data.get("issues_found", [])
            improvements_made = data.get("improvements_made", [])
            confidence = data.get("confidence", 0.9)
            logger.info("Structured LLM Output - Issues: %s, Improvements: %s, Confidence: %s", issues_found, improvements_made, confidence)
        else:
            email_draft = raw_response
    except Exception as exc:
        logger.warning("Failed to parse structured LLM JSON: %s. Falling back to raw text.", exc)
        email_draft = raw_response

    # Validate output and run safety checks
    if not email_draft:
        logger.warning("LLM returned empty draft output")
        raise ValueError("Empty draft generated by LLM")

    # Safety checks
    passed, safety_issues = _run_outreach_safety_checks(email_draft, selected_vendor)
    if not passed:
        logger.warning("AI Safety check flagged issues: %s", safety_issues)
        # Automatic healing of placeholders
        for ph in ["[Vendor Name]", "[Recipient's Last Name]", "[Recipient's Name]", "[Contact Name]", "[First Name]", "[Last Name]"]:
            if ph in email_draft:
                replace_name = (selected_vendor.get("vendor_name") or selected_vendor.get("name") or "Vendor Team") if selected_vendor else "Vendor Team"
                email_draft = email_draft.replace(ph, replace_name)

        if not email_draft.strip():
            email_draft = f"Dear Team,\n\nWe are interested in discussing procurement opportunities for your services. Please let us know your availability.\n\nBest regards,\n{config.DEFAULT_USER_NAME}\n{config.DEFAULT_COMPANY_NAME}"

    # Defensive truncation
    email_draft = email_draft[:MAX_OUTPUT_LENGTH]

    logger.info("Draft generation completed")
    return email_draft


async def self_reflect_draft(draft: str, prompt: str, rejection_feedback: Optional[str] = None) -> str:
    """
    Reviews and improves an outreach message using a two-pass LLM approach:
    Pass 1: Internal evaluation (generates improvement suggestions, not returned to user).
    Pass 2: Rewrite using evaluation insights (returned as the improved draft).
    """
    logger.info("Self-reflection started (provider=%s, model=%s)", config.AGENT_PROVIDER, _get_model())

    # --- Pass 1: Internal evaluation (not returned to user) ---
    evaluation_prompt = (
        f"Evaluate this outreach draft for professionalism, clarity, persuasion, "
        f"specificity, and business tone. List 2-3 concrete improvement suggestions.\n\n"
        f"Draft:\n{draft}"
    )
    _log_llm_used("self_reflect_pass1_evaluation")
    try:
        eval_response = await get_client().chat.completions.create(
            model=_get_model(),
            messages=[
                {
                    "role": "system",
                    "content": "You are a senior procurement communication reviewer. Provide a brief internal evaluation."
                },
                {
                    "role": "user",
                    "content": evaluation_prompt
                }
            ],
            temperature=config.REFLECTION_TEMPERATURE,
            max_tokens=200
        )
        _log_usage("self_reflect_pass1_evaluation", eval_response)
        evaluation = eval_response.choices[0].message.content.strip()
        logger.info("Self-reflection pass 1 (evaluation) completed")
    except Exception:
        logger.warning("Self-reflection pass 1 failed, proceeding with direct rewrite")
        evaluation = "Improve professionalism, clarity, and business tone."

    # --- Pass 2: Rewrite using evaluation insights ---
    rewrite_content = (
        f"Original task:\n{prompt}\n\n"
        f"Internal evaluation notes:\n{evaluation}\n\n"
        f"Current outreach draft:\n{draft}\n\n"
    )
    if rejection_feedback:
        rewrite_content += (
            f"Mandatory user feedback. These instructions override internal evaluation notes if there is any conflict:\n"
            f"'{rejection_feedback}'\n\n"
        )
    rewrite_content += (
        "Rewrite the draft into a polished, professional procurement outreach email "
        "that addresses all evaluation points while strictly following the mandatory user feedback.\n\n"
        "Return ONLY the rewritten email. No commentary, no headings, no analysis."
    )
    _log_llm_used("self_reflect_pass2_rewrite")
    try:
        response = await get_client().chat.completions.create(
            model=_get_model(),
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a professional email writer. "
                        "Return ONLY the final rewritten outreach email. "
                        "Do NOT include any evaluation, commentary, markdown headings, "
                        "bullet points, or analysis text. "
                        "Strictly follow the user's rejection feedback for language, length, and format. "
                        "If the feedback asks for one line, return one line only. "
                        "NEVER replace specific vendor or company names with placeholders like "
                        "[Recipient's Last Name], [First Name], [Vendor Name], or any bracket text. "
                        "If the original draft addresses a specific company, preserve that company name. "
                        "Address the email to the vendor company team directly (e.g., 'Dear <CompanyName> Team,')."
                    )
                },
                {
                    "role": "user",
                    "content": rewrite_content
                }
            ],
            temperature=config.REFLECTION_TEMPERATURE,
            max_tokens=300
        )
    except Exception:
        logger.exception("LLM request failed during self-reflection pass 2 (provider=%s)", config.AGENT_PROVIDER)
        raise

    _log_usage("self_reflect_pass2_rewrite", response)
    improved = response.choices[0].message.content.strip()

    # Validate LLM output
    if not improved:
        logger.warning("LLM returned empty self-reflection output")
        raise ValueError("Empty self-reflection output generated by LLM")

    # Defensive sanitization: strip any leaked evaluation/critique preamble
    # Uses regex to detect and remove non-email content before the actual message
    critique_pattern = re.compile(
        r'^.*?(?=(?:Subject:|Dear\s|To\s*:))',
        re.DOTALL | re.IGNORECASE
    )
    match = critique_pattern.match(improved)
    if match:
        preamble = match.group(0).lower()
        critique_keywords = ["evaluation", "professionalism", "critique", "clarity",
                             "persuasion", "assessment", "analysis", "rating", "score"]
        if any(kw in preamble for kw in critique_keywords):
            improved = improved[match.end():]
            logger.info("Sanitized leaked evaluation preamble from LLM output")

    # Strip leading/trailing markdown artifacts (```, ##, etc.)
    improved = re.sub(r'^[`#\-\s]+', '', improved).strip()
    improved = re.sub(r'[`]+$', '', improved).strip()

    # Defensive truncation
    improved = improved[:MAX_OUTPUT_LENGTH]

    logger.info("Self-reflection completed (two-pass)")
    return improved
